### ISSUE TITLE
tukui client login

### ISSUE THREAD

**Issue by fyrbeast** [tukui-org/Tukui#104]
Had everything set to save user/password and keep me logged in. Out of the blue it deleted it and there is no tab/ link to click to reset and most every tukui link I search goes to a download page.

How does one reset their password and search for there username?

I have tried uninstalling and reinstalling hoping for fresh prompts to create user/password to no avail.

**Comment by Azilroka** [comment]
There is an announcement on discord concerning the state of the site.

**Comment by fyrbeast** [comment]
never have used discord.

**Comment by Repooc** [comment]
![image](https://github.com/tukui-org/Tukui/assets/1479745/24f2d7ee-2249-4b72-9ec3-7d63ecc7acd3)
