### ISSUE TITLE
install tukui client win 11

### ISSUE THREAD

**Issue by Bladesoldier90** [tukui-org/Tukui#105]
Greetings,
I wanted to know why downloading the new tukui client doesn't give me the exe file to install it on my windows 11?
could you tell me how to do?
Thank you

**Comment by DarthPredator** [comment]
Tukui client isn't a thing anymore starting this month
![image](https://github.com/tukui-org/Tukui/assets/487494/6c5ba8c7-9363-4ca1-97bc-f41f7945aba5)
