### ISSUE TITLE
[Retail] ALT_MANA_BAR Lua Error

### ISSUE THREAD

**Issue by Numira123** [tukui-org/Tukui#112]
Message: ...s/Tukui/Libs/oUF_Retail/elements/powerprediction.lua:70: attempt to index upvalue 'ALT_MANA_BAR_PAIR_DISPLAY_INFO' (a nil value)
Time: Thu Jul 13 10:46:41 2023
Count: 12
Stack: ...s/Tukui/Libs/oUF_Retail/elements/powerprediction.lua:70: attempt to index upvalue 'ALT_MANA_BAR_PAIR_DISPLAY_INFO' (a nil value)
[string "@Interface/AddOns/Tukui/Libs/oUF_Retail/elements/powerprediction.lua"]:70: in function <...s/Tukui/Libs/oUF_Retail/elements/powerprediction.lua:52>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Tukui/Libs/oUF_Retail/events.lua"]:79: in function <Interface/AddOns/Tukui/Libs/oUF_Retail/events.lua:77>
[string "=(tail call)"]: ?

Locals: self = TukuiPlayerFrame {
 0 = <userdata>
 Shadow = Frame {
 }
 HealthPrediction = <table> {
 }
 __tags = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/ouf.lua:53
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/castbar.lua:178
 unitEvents = <table> {
 }
 UNIT_MAXHEALTH = <table> {
 }
 __elements = <table> {
 }
 Panel = Frame {
 }
 PowerPrediction = <table> {
 }
 Power = StatusBar {
 }
 UNIT_HEAL_ABSORB_AMOUNT_CHANGED = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/healthprediction.lua:197
 UNIT_SPELLCAST_NOT_INTERRUPTIBLE = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/castbar.lua:387
 PLAYER_REGEN_DISABLED = <function> defined @Interface/AddOns/Tukui/Modules/UnitFrames/Core.lua:277
 UNIT_HEALTH = <table> {
 }
 style = "Tukui"
 UNIT_SPELLCAST_CHANNEL_STOP = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/castbar.lua:334
 RAID_TARGET_UPDATE = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/raidtargetindicator.lua:62
 UNIT_EXITED_VEHICLE = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/ouf.lua:53
 UNIT_SPELLCAST_INTERRUPTIBLE = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/castbar.lua:387
 UNIT_CONNECTION = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/health.lua:139
 Debuffs = TukuiPlayerFrameDebuffs {
 }
 UNIT_SPELLCAST_INTERRUPTED = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/castbar.lua:356
 UNIT_HEAL_PREDICTION = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/healthprediction.lua:197
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/castbar.lua:277
 MasterLooterIndicator = Texture {
 }
 RaidTargetIndicator = Texture {
 }
 unit = "player"
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/castbar.lua:277
 UNIT_SPELLCAST_EMPOWER_UPDATE = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/castbar.lua:277
 UNIT_SPELLCAST_SUCCEEDED = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/powerprediction.lua:129
 PLAYER_REGEN_ENABLED = <function> defined @Interface/AddOns/Tukui/Modules/UnitFrames/Core.lua:277
 Status = Texture {
 }
 UNIT_SPELLCAST_STOP = <table> {
 }
 UNIT_AURA = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/auras.lua:289
 UNIT_SPELLCAST_EMPOWER_START = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/castbar.lua:178
 UNIT_DISPLAYPOWER = <table> {
 }
 UNIT_SPELLCAST_EMPOWER_STOP = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/castbar.lua:334
 AdditionalPower = TukuiPlayerFrameAdditionalPower {
 }
 CombatIndicator = Texture {
 }
 LeaderIndicator = Texture {
 }
 UNIT_SPELLCAST_START = <table> {
 }
 Backdrop = Frame {
 }
 UNIT_ABSORB_AMOUNT_CHANGED = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/elements/healthprediction.lua:197
 Health = StatusBar {
 }
 RestingIndicator = Texture {
 }
 Name = FontString {
 }
 UNIT_ENTERED_VEHICLE = <function> defined @Interface/AddOns/Tukui/Libs/oUF_Retail/ouf.lua:53
 Castbar = TukuiPlayerCastBar {
 }
 Buffs = TukuiPlayerFrameBuffs {
 }
 Comb

**Comment by JerichoR** [comment]
Already fixed in Dev version, just not released yet.
