### ISSUE TITLE
Raid Frames Disappar / Reappear

### ISSUE THREAD

**Issue by Zalliano** [tukui-org/Tukui#114]
For 2 months now same issue.  On Elvui my raid frames will disappear on their own and reappear on their own.  In and out of combat. I have checked all my settings. CAn you please fix this.

**Comment by Repooc** [comment]
This is tukui ticket system not elvui

**Comment by Zalliano** [comment]
Doesnt tukui make Elvui ?

**Comment by Azilroka** [comment]
Tukui is a UI.. ElvUI is a UI.. 2 completely different UI's
