### ISSUE TITLE
Raid Frasmes Disappear

### ISSUE THREAD

**Issue by Zalliano** [tukui-org/Tukui#115]
For 2 months now same issue. On Elvui my raid frames will disappear on their own and reappear on their own. In and out of combat. I have checked all my settings. CAn you please fix this.

**Comment by Zalliano** [comment]
Doesn't Tukui make Elvui?  Gotta link where I should go ?  How do I directly contact Elvui? Phone? Email?

**Comment by Azilroka** [comment]
Tukui is a UI.. ElvUI is a UI.. 2 completely different UI's

**Comment by Azilroka** [comment]
https://github.com/tukui-org/ElvUI

**Comment by Zalliano** [comment]
Thanks  but still no direct way to contact people at Elvui

**Comment by Repooc** [comment]
> Thanks but still no direct way to contact people at Elvui

Discord Url is on our home page https://tukui.org

Assuming you mean live text with others to help as we have a bunch of users there to help.
