### ISSUE TITLE
[Classic-Era] Error after new patch

### ISSUE THREAD

**Issue by theraad3k** [tukui-org/Tukui#116]
![image](https://github.com/tukui-org/Tukui/assets/143010165/060d51f3-07be-40a0-b31b-8698b2340830)

Hello, have this error after new patch 1.14.4.51001

**Comment by naseimsand** [comment]
As a workaround you can disable Lua Errors with this command:

/console scriptErrors 0

**Comment by Repooc** [comment]
this is not a work around as its hiding an error and not solving it. the error is no longer a thing in the dev build just sorting isnt in working order though
