### ISSUE TITLE
Mana as an option for a tag on a unit frame

### ISSUE THREAD

**Issue by robbie5656** [tukui-org/Tukui#12]
In older versions of Tukui I was able to have my my mana display on the left hand side of my player user frame. Now I only have health options for the right side and my name and level on the left. As an arcane mage, the amount of mana I have is important for me to know and useful when discussing gear with other players. Currently, I have to join a party to be able to see that value. Is there a way to add this as an option again, or could you tell me where I could make the change in the lua? Thanks!

**Comment by robnadin** [comment]
Do you have a screenshot of how it looked in the old UI by any chance?

I can create a PR for this as on paper it looks trivial to add - but I want to make sure it's what you were expecting!

**Comment by robbie5656** [comment]
I might on my old laptop but I'm not at my place for the next week so I can't look for one. There are a couple things I can show you that might give you an idea:

I had found a older post with instructions on how to edit a lua file to replace your name and level with your current mana value. It seems that was broken in the latest update of Tukui bc I can't recreate it. Here is what the edit looked like before the latest update: 
![image](https://user-images.githubusercontent.com/71793533/154723735-e904feff-3401-4e38-81a7-5fdbd46d52fb.png)
Ideally, it would be great to have all three values there for a caster. But if I have to chose two, my hp and mana are more important than my name and level. Knowing how much mana I have when I'm out of combat lets me compare with other mages and switch in and out pieces. Maybe we could have mana on the left and hp on the right like my pic shows, and then name and user in the middle. 

As for people on other posts saying you can see mana when you're in combat, that is true when I'm in combat but not doing anything. When I'm casting 1.5 second arcane blasts all I can see is my cast bar b/c it's in the same location as where the info is. Not knowing the actual mana value on a fight like Kaz'rogal could kill you and wipe your raid. 
![image](https://user-images.githubusercontent.com/71793533/154724553-73ba8e07-0d72-43b0-9e33-b69efae8fa53.png)

Sorry for the lengthy post, hopefully it was helpful. I'm just psyched to get a reply on this issue. It would be a huge quality of life boost for me. Thanks @robnadin !

**Comment by robnadin** [comment]
So I believe the option you're looking for is still in Tukui, so it may not be what you have been looking for all this time!

In the screenshot below, you need to turn the highlighted option **off**:
<img width="698" alt="Screenshot 2022-02-18 at 11 07 34 pm" src="https://user-images.githubusercontent.com/536914/154773004-9fc8defa-600e-4a40-b7ee-830e6ecf5a1e.png">

Disabling this means your mana will show 100% of the time now, rather than just in combat.

If you really want the ability to still show your character's name and level in addition to your mana and health, I'd probably say raise it as a separate issue 🙂

**Comment by robbie5656** [comment]
I have looked at the settings so many times and never thought to click that off. Thank you so much! @robnadin
