### ISSUE TITLE
[BCC] Castbar continues moving even after cast is cancelled

### ISSUE THREAD

**Issue by t3hWheez** [tukui-org/Tukui#13]
Ignore my work meeting audio.

https://youtu.be/Iny4zkfP124

**Comment by addohm** [comment]
![image](https://user-images.githubusercontent.com/25333107/150044173-31e2952f-10f2-4d29-9a98-c0fc1f25bc14.png)

Disabled UF for now as disabling cast bars does not stop this error.

**Comment by Exilza** [comment]
Did you solve this? got the same problem.

**Comment by Azilroka** [comment]
Yes.  Did you check for an update?
