### ISSUE TITLE
MIssing Item Level when Comparing 

### ISSUE THREAD

**Issue by sidarthus89** [tukui-org/Tukui#130]
Not sure if this is Blizz or Tukui. When i shift click on an item for sale or as a reward to compare it to what i have equipped, there is no listed item level

![image](https://github.com/tukui-org/Tukui/assets/111938061/36a4dbf7-4a76-4d75-8600-2a092468beed)

**Comment by Repooc** [comment]
Disable all addons and look to see if it's there
