### ISSUE TITLE
Getting this error not sure what it entails. SetBackDrop ( a nil value) tbc classic

### ISSUE THREAD

**Issue by Zuluking91** [tukui-org/Tukui#14]
Message: Interface\AddOns\Tukui\Modules\Tooltips\Tooltips.lua:388: attempt to call method 'SetBackdrop' (a nil value)
Time: Wed Jan 19 10:59:03 2022
Count: 1
Stack: Interface\AddOns\Tukui\Modules\Tooltips\Tooltips.lua:388: attempt to call method 'SetBackdrop' (a nil value)
[string "*:OnHide"]:1: in function <[string "*:OnHide"]:1>
[string "=[C]"]: ?

Locals: self = GameTooltip {
 0 = <userdata>
 Shadow = <unnamed> {
 }
 GetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:182
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105
 SetVoidItem = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:186
 SetVoidDepositItem = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105
 SetVoidWithdrawalItem = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105
 SetCraftItem = <function> defined =[C]:-1
 IsSkinned = true
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:190
 __tamedCounts = false
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:194
 SetTrainerService = <function> defined =[C]:-1
 Backdrop = <unnamed> {
 }
 Hide = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 SetRecipeReagentItem = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105
 SetBuybackItem = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105
 shoppingTooltips = <table> {
 }
 SetCraftSpell = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105
 SetQuestLogItem = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105
 SetTradePlayerItem = <function> defined =[C]:-1
 updateTooltip = 0.167000
 SetSendMailItem = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 NineSlice = <unnamed> {
 }
 SetInventoryItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105
 TooltipBackdropOnLoad = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:163
 SetUnitAura = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetAction = <function> defined =[C]:-1
 SetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:178
 BottomOverlay = <unnamed> {
 }
 SetAuctionItem = <function> defined =[C]:-1
}

**Comment by Tiolius** [comment]
After today WoW (TBC version) update I have same issue, Problem in Tooltip module. Temporarily disabled it in settings to get rid of errors.

**Comment by Zuluking91** [comment]
Alright thanks so just wait for update on tukui. Thanks, im home with covid and my head isnt working properly. Only just then saw tooltip when you mentioned it.

**Comment by Tiolius** [comment]
Issue fixed, as it turned out, the fixes have already been made to the addon, just download the updated version from the section Code or wait when addon will be updated on another sites.

**Comment by Zuluking91** [comment]
For me it says its 6 days old the last update. Is that it?

**Comment by Tiolius** [comment]
Yea, tukz made fixes on PTR. So this version work fine even if it's 6 days ago.

**Comment by Zuluking91** [comment]
Alright cheers :)
