### ISSUE TITLE
TUKUI LUA Error WoW Version 10.2.5.53262

### ISSUE THREAD

**Issue by WCLauritzen** [tukui-org/Tukui#141]
Message: Interface/AddOns/Tukui/Modules/ActionBars/Skin.lua:118: attempt to index local 'RightDivider' (a nil value)
Time: Tue Feb 20 09:54:16 2024
Count: 1
Stack: Interface/AddOns/Tukui/Modules/ActionBars/Skin.lua:118: attempt to index local 'RightDivider' (a nil value)
[string "@Interface/AddOns/Tukui/Modules/ActionBars/Skin.lua"]:118: in function `SkinButton'
[string "@Interface/AddOns/Tukui/Modules/ActionBars/Bar1.lua"]:172: in function `CreateBar1'
[string "@Interface/AddOns/Tukui/Modules/ActionBars/Core.lua"]:512: in function `Enable'
[string "@Interface/AddOns/Tukui/Core/Loading.lua"]:293: in function <Interface/AddOns/Tukui/Core/Loading.lua:241>
[string "=[C]"]: in function `NotifySettingsLoaded'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsRegistrar.lua"]:19: in function <...ce/SharedXML/Settings/Blizzard_SettingsRegistrar.lua:11>
[string "@Interface/SharedXML/EventUtil.lua"]:21: in function <Interface/SharedXML/EventUtil.lua:15>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:178: in function <Interface/SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@Interface/SharedXML/GlobalCallbackRegistry.lua"]:9: in function <Interface/SharedXML/GlobalCallbackRegistry.lua:8>

Locals: self = Frame {
 DisableBlizzard = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Core.lua:25
 UpdatePetBarCooldownText = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Core.lua:211
 UpdateStanceBar = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Core.lua:235
 CreateBar7 = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Bar7.lua:6
 MoveStanceButtons = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/BarStance.lua:5
 StyleFlyout = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Skin.lua:273
 StopHightlight = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Core.lua:374
 SkinPetButtons = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Skin.lua:234
 AddHooks = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Core.lua:455
 SkinFlyoutButtons = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Skin.lua:256
 UpdatePetBar = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Core.lua:80
 SkinZoneAbilities = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Extra.lua:20
 CreateBar8 = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Bar8.lua:6
 OnUpdatePetBarCooldownText = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Core.lua:190
 CreateBar1 = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Bar1.lua:7
 CreateBar5 = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Bar5.lua:6
 StartHighlight = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Core.lua:348
 CreateBar2 = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Bar2.lua:6
 StopButtonHighlight = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Skin.lua:305
 SkinStanceButtons = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Skin.lua:245
 CreateStanceBar = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/BarStance.lua:13
 SkinButton = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Skin.lua:9
 RangeUpdate = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Core.lua:306
 UpdateButton = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Core.lua:434
 UpdateMultiCastBar = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Core.lua:487
 DisableExtraButtonTexture = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Extra.lua:10
 0 = <userdata>
 SkinPetAndShiftButton = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Skin.lua:155
 SetHotKeyText = <function> defined @Interface/AddOns/Tukui/Modules/ActionBars/Core.lua:384
 Enable = <

**Comment by rookwood** [comment]
This was fixed in c1185e8e948b45656d923f79af655c348f58a47e.  Use the dev version instead of the live release for now.

**Comment by WCLauritzen** [comment]
G'day so I was using the retail version from the https://tukui.org/tukui website.

I have downloaded the live version from the github and it works now but still produces the same error.

Date: 2024-03-23 12:39:51
ID: 1
Error occured in: Global
Count: 10
Message: Interface/FrameXML/MainMenuBarMicroButtons.lua line 1623:
   attempt to compare two nil values
Debug:
   [string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:1623: GetEdgeButton()
   [string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:1651: UpdateHelpTicketButtonAnchor()
   [string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:1710: Layout()
   [string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:1759: Layout()
   [string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:413:
      Interface/FrameXML/MainMenuBarMicroButtons.lua:412
   [string "=[C]"]: ?
   [string "=[C]"]: Hide()
   [string "@Interface/AddOns/Tukui/Modules/Miscellaneous/MicroMenu.lua"]:272: Enable()
   [string "@Interface/AddOns/Tukui/Modules/Miscellaneous/Core.lua"]:16: Enable()
   [string "@Interface/AddOns/Tukui/Core/Loading.lua"]:262:
      Interface/AddOns/Tukui/Core/Loading.lua:241
Locals:
self = MicroMenu {
 IsLayoutFrame = <function> defined @Interface/SharedXML/LayoutFrame.lua:36
 GetEdgeButton = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1600
 ShouldUpdateLayout = <function> defined @Interface/SharedXML/LayoutFrame.lua:483
 MarkDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:99
 SetHeightPadding = <function> defined @Interface/SharedXML/LayoutFrame.lua:160
 layoutFramesGoingRight = true
 OnCleaned = <function> defined @Interface/SharedXML/LayoutFrame.lua:131
 isHorizontal = true
 OnUpdate = <function> defined @Interface/SharedXML/LayoutFrame.lua:93
 GetAdditionalRegions = <function> defined @Interface/SharedXML/LayoutFrame.lua:85
 GetFixedSize = <function> defined @Interface/SharedXML/LayoutFrame.lua:156
 OnShow = <function> defined @Interface/SharedXML/LayoutFrame.lua:32
 GetHeightPadding = <function> defined @Interface/SharedXML/LayoutFrame.lua:164
 UpdateFramerateFrameAnchor = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1666
 GetFixedWidth = <function> defined @Interface/SharedXML/LayoutFrame.lua:148
 dirty = false
 stride = 12
 GetWidthPadding = <function> defined @Interface/SharedXML/LayoutFrame.lua:168
 childYPadding = -5
 SetScaleAdjustment = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1713
 layoutFramesGoingUp = false
 UpdateQueueStatusAnchors = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1656
 SetFixedWidth = <function> defined @Interface/SharedXML/LayoutFrame.lua:135
 InitializeButtons = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1565
 GetFixedHeight = <function> defined @Interface/SharedXML/LayoutFrame.lua:152
 MarkClean = <function> defined @Interface/SharedXML/LayoutFrame.lua:117
 CacheLayoutSettings = <function> defined @Interface/SharedXML/LayoutFrame.lua:471
 SetFixedSize = <function> defined @Interface/SharedXML/LayoutFrame.lua:143
 GetLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:73
 numButtons = 12
 IsDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:127
 OnLoad = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1560
 oldGridSettings = <table> {
 }
 Layout = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1703
 SetFixedHeight = <function> defined @Interface/SharedXML/LayoutFrame.lua:139
 AnchorToMenuContainer = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1674
 SetQueueStatusScale = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1695
 0 = <userdata>
 UpdateHelpTicketButtonAnchor = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1634
 AddButton = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:1591
 MarkIgnoreInLayout = <function> defined @Interface/SharedXML/LayoutFrame.lua:44
 AddLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:55
 childXPadding = -5
 IgnoreLayoutIndex = <function> defined @Interface/SharedXML/LayoutFrame.lua:515
}
rightMost = false
topMost = true
firstButton = HelpMicroButton {
 0 = <userdata>
 OnEnter = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:353
 FlashBorder = Texture {
 }
 QuickKeybindButtonOnShow = <function> defined @Interface/FrameXML/QuickKeybind.lua:4
 QuickKeybindButtonOnEnter = <function> defined @Interface/FrameXML/QuickKeybind.lua:22
 DoModeChange = <function> defined @Interface/FrameXML/QuickKeybind.lua:95
 QuickKeybindButtonOnUpdate = <function> defined @Interface/FrameXML/QuickKeybind.lua:75
 tooltipText = "Customer Support"
 QuickKeybindButtonOnLeave = <function> defined @Interface/FrameXML/QuickKeybind.lua:33
 OnMouseDown = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:416
 Background = Texture {
 }
 PushedBackground = Texture {
 }
 QuickKeybindButtonSetTooltip = <function> defined @Interface/FrameXML/QuickKeybind.lua:52
 layoutIndex = 10
 OnShow = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.lua:408
 OnLoad = <function> defined @Interface/FrameXML/MainMenuBarMicroButtons.l
AddOns:
  Swatter, v9.1.BETA.5.13 (OneMawTime)
  Auctioneer, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.13 (OneMawTime)
  DBMArchaeology, vr59
  DBMCore, v10.2.31
  DBMCountPackOverwatch, v1.4.39
  DBMFlightTimers, v@project-version@
  DBMSoundEventsPack, v1.6.33
  DBMStatusBarTimers, v10.2.31
  DBMVPVEM, v2ac85f8
  Enchantrix, v9.1.BETA.5.13 (OneMawTime)
  Informant, v9.1.BETA.5.13 (OneMawTime)
  Recount, vv10.2.5a
  Stubby, v9.1.BETA.5.13 (OneMawTime)
  Tukui, v20.41 
  BlizRuntimeLib v10.2.6.53877(US) <enUS>
  (ck=281)

I am going to try the dev version and see if it reproduces the error as recommended above.

**Comment by WCLauritzen** [comment]
> This was fixed in [c1185e8](https://github.com/tukui-org/Tukui/commit/c1185e8e948b45656d923f79af655c348f58a47e). Use the dev version instead of the live release for now.

Just tried that version and it still produces the same error as other versions except it works now.

**Comment by rookwood** [comment]
> still produces the same error

You have to read the error message.  This is a different error from the one you were getting previously.

**Comment by JerichoR** [comment]
@tukz this issue is also fixed. the second issue mentioned in comment is still there though. We currently set Tukui -> Misc -> Micromenu to "none", that one works
