### ISSUE TITLE
SoD Rune Lifebloom error

### ISSUE THREAD

**Issue by mahald** [tukui-org/Tukui#144]
Always if i use the Lifebloom rune as druid with tukui i get the error:

Message: ...ddOns/Tukui/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:818: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
Time: Wed Feb 28 18:53:25 2024
Count: 9
Stack: ...ddOns/Tukui/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:818: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
[string "@Interface/AddOns/Tukui/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:818: in function <...ddOns/Tukui/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:807>
[string "@Interface/AddOns/Tukui/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:967: in function <...ddOns/Tukui/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:965>
[string "@Interface/AddOns/Tukui/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:2706: in function `?'
[string "@Interface/AddOns/Tukui/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:3348: in function <...ddOns/Tukui/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:3346>

Locals: spellData = <table> {
 levels = <table> {
 }
 bomb = <table> {
 }
 coeff = 0.520000
 interval = 1
 ticks = 7
 averages = <table> {
 }
 dhCoeff = 0.343350
}
spellName = "Lifebloom"
spellID = 408124
spellRank = nil
average = nil
requiresLevel = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 11
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'requiresLevel' (a nil value)"
type = <function> defined =[C]:-1
min = <function> defined =[C]:-1
playerLevel = 11

**Comment by JerichoR** [comment]
@tukz this should be fixed by your latest merge [#134 ](https://github.com/tukui-org/Tukui/pull/134)
