### ISSUE TITLE
wrong logical calculations

### ISSUE THREAD

**Issue by AdenJustice** [tukui-org/Tukui#150]
They should be "and" not "or" in the following line

https://github.com/tukui-org/Tukui/blob/6f027b27e9800c397ecc9bb8ac8cef48b42f2907/Tukui/Config/Gui.lua#L25

**Comment by thurin** [comment]
I don't think so.  How would you have all 3 locales at the same time?

**Comment by kodewdle** [comment]
thank you 🌼
