### ISSUE TITLE
Action bars dont load in Classic Cata

### ISSUE THREAD

**Issue by sidarthus89** [tukui-org/Tukui#152]
Message: Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:1401: attempt to call upvalue 'SetSortBagsRightToLeft' (a nil value)
Time: Fri May 10 21:11:52 2024
Count: 1
Stack: Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:1401: attempt to call upvalue 'SetSortBagsRightToLeft' (a nil value)
[string "@Interface/AddOns/Tukui/Modules/Inventory/Bags.lua"]:1401: in function `Enable'
[string "@Interface/AddOns/Tukui/Modules/Inventory/Core.lua"]:6: in function `Enable'
[string "@Interface/AddOns/Tukui/Core/Loading.lua"]:249: in function <Interface/AddOns/Tukui/Core/Loading.lua:241>

Locals: self = Frame {
 0 = <userdata>
 CloseBag = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:1156
 CreateContainer = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:372
 UpdateAllBankBags = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:1027
 OpenAllBags = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:1160
 ToggleBags = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:1242
 CreateReagentContainer = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:246
 SetTokensPosition = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:62
 HideBlizzard = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:162
 Enable = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:1390
 BagUpdate = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:872
 OpenBag = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:1102
 ToggleReagents = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:1373
 GetBagType = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:91
 CloseAllBankBags = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:1233
 CloseAllBags = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:1219
 OnEvent = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:1286
 OpenAllBankBags = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:1182
 SlotUpdate = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:653
 GetBagProfessionType = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:83
 SkinBagButton = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:105
 UpdateCooldown = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:857
 CooldownOnUpdate = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:835
 UpdateAllBags = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:931
 MoveElements = <function> defined @Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:226
}
(*temporary) = nil
(*temporary) = true
(*temporary) = "attempt to call upvalue 'SetSortBagsRightToLeft' (a nil value)"
C = <table> {
 Misc = <table> {
 }
 General = <table> {
 }
 ActionBars = <table> {
 }
 Bags = <table> {
 }
 Tooltips = <table> {
 }
 Chat = <table> {
 }
 Medias = <table> {
 }
 Party = <table> {
 }
 Loot = <table> {
 }
 Raid = <table> {
 }
 Textures = <table> {
 }
 Maps = <table> {
 }
 DataTexts = <table> {
 }
 UnitFrames = <table> {
 }
 Cooldowns = <table> {
 }
 NamePlates = <table> {
 }
 Auras = <table> {
 }
}
SetSortBagsRightToLeft = nil
SetInsertItemsLeftToRight = <function> defined =[C]:-1
T = Frame {
 0 = <userdata>
 MyName = "Kìljaeden"
 Help = TukuiHelp {
 }
 MyRealm = "Maladath"
 WindowedMode = false
 WoWBuild = 54558
 TextureTable = <table> {
 }
 WoWPatch = "4.4.0"
 IconCoord = <table> {
 }
 ScreenWidth = 1920
 Profiles = TukuiProfiles {
 }
 UnusedTimers = <table> {
 }
 MyFaction = "Alliance"
 FontTable = <table> {
 }
 BCC = false
 GetFont = <function> defined @Interface/AddOns/Tukui/Core/Media.lua:68
 FullscreenMode = true
 ColorGradient = <function> defined @Interface/AddOns/Tukui/Core/Core.lua:94
 ScreenHeight = 1080
 ShortValue = <function

**Comment by ury2000** [comment]
I love Tukui UI, it would be very nice to use it in Cataclysm Classic, I was trying it today and the same thing happens to me as described before. 

I hope you can solve it...

Greatings !!
