### ISSUE TITLE
Bag Cleanup Button Covered by SIde Action Bars

### ISSUE THREAD

**Issue by sidarthus89** [tukui-org/Tukui#153]
![image](https://github.com/tukui-org/Tukui/assets/111938061/752412dd-0fd2-43b1-bf8f-b10c7990ce5a)

**Comment by JerichoR** [comment]
That was caused by the "fix" to bags where the background covered all items. Hopefully for TWW that will also be cleaned up again.

**Comment by sidarthus89** [comment]
Issue not resolved with update as of this morning.
