### ISSUE TITLE
Lua Issue + Can't Clean up Bags

### ISSUE THREAD

**Issue by sidarthus89** [tukui-org/Tukui#158]
Just installed the latest code from 10 hours ago.
 
 TukUI loads and looks fine just gets this LUA error

Message: Interface/AddOns/Tukui/Tukui-Cata.toc:20 Error loading Interface/AddOns/Tukui/Libs/LibStub/LibStub.lua
Time: Mon Jul 15 11:59:51 2024
Count: 2

Additionally, cannot cleanup bag

**Comment by sidarthus89** [comment]
Error when trying to clean up bags:

Date: 2024-07-15 12:10:35
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Tukui/Modules/Inventory/Bags.lua line 520:
   attempt to call local 'Sort' (a nil value)
Debug:
   [string "@Interface/AddOns/Tukui/Modules/Inventory/Bags.lua"]:520:
      Interface/AddOns/Tukui/Modules/Inventory/Bags.lua:511
Locals:
Sort = nil
(*temporary) = nil
(*temporary) = "attempt to call local 'Sort' (a nil value)"
T = Frame {
 0 = <userdata>
 MyName = "Sidarthus"
 Help = TukuiHelp {
 }
 MyRealm = "Mankrik"
 WindowedMode = false
 WoWBuild = 55613
 TextureTable = <table> {
 }
 WoWPatch = "4.4.0"
 IconCoord = <table> {
 }
 ScreenWidth = 1920
 Profiles = TukuiProfiles {
 }
 UnusedTimers = <table> {
 }
 MyFaction = "Alliance"
 FontTable = <table> {
 }
 BCC = false
 GetFont = <function> defined @Interface/AddOns/Tukui/Core/Media.lua:68
 FullscreenMode = true
 ColorGradient = <function> defined @Interface/AddOns/Tukui/Core/Core.lua:94
 ScreenHeight = 1080
 ShortValue = <function> defined @Interface/AddOns/Tukui/Core/Core.lua:30
 WoWPatchReleaseDate = "Jul 11 2024"
 Maps = Frame {
 }
 SlashHandler = <function> defined @Interface/AddOns/Tukui/Core/Commands.lua:30
 MyClass = "DEATHKNIGHT"
 NewTimer = <function> defined @Interface/AddOns/Tukui/Core/Core.lua:128
 Version = "Development"
 UnitAura = <function> defined @Interface/AddOns/Tukui/Core/Core.lua:138
 Retail = false
 ActionBars = Frame {
 }
 Comma = <function> defined @Interface/AddOns/Tukui/Core/Core.lua:41
 Cata = true
 WotLK = false
 AddOnCommands = <table> {
 }
 TestUI = Frame {
 }
 Hider = TukuiHider {
 }
 DataTexts = Frame {
 }
 PerfectScale = 0.711111
 Fonts = Frame {
 }
 MyRace = "Human"
 Colors = <table> {
 }
 Cooldowns = Frame {
 }
 VersionNumber = 99999
 PetHider = TukuiPetHider {
 }
 TocVersion = 40400
 DF = false
 Print = <function> defined @Interface/AddOns/Tukui/Core/Core.lua:16
 Install = Frame {
 }
 Toolkit = T00LKIT {
 }
 Defaults = <table> {
 }
 Themes = <table> {
 }
 Loading = Frame {
 }
 Round = <function> defined @Interface/AddOns/Tukui/Core/Core.lua:47
 GUI = TukuiGUI {
 }
 UnitFrames = Frame {
 }
 TWW = false
 RGBToHex = <function> defined @Interface/AddOns/Tukui/Core/Core.lua:21
 Tooltips = Frame {
 }
 Movers = TukuiMovers {
 }
 Media = Frame {
 }
 GetTexture = <function> defined @Interface/AddOns/Tukui/Core/Media.lua:76
 Inventory = Frame {
 }
 Miscellaneous = Frame {
 }
 Classic = false
 FormatTime = <function> defined @Interface/AddOns/Tukui/Core/Core.lua:56
 Chat = Frame {
 }
 MyLevel = 85
 Auras = Frame {
 }
 Resolution = "1920x1080"
 Popups = Frame {
 }
 OffScreen = TukuiOffScreen {
 }
}

AddOns:
  Swatter, v4.4.6991 (SwimmingSeadragon)
  AucAdvanced, v4.4.6991 (SwimmingSeadragon)
  AucFilterBasic, v4.4.6991 (SwimmingSeadragon)
  AucScanData, v4.4.6991 (SwimmingSeadragon)
  AucStatHistogram, v4.4.6991 (SwimmingSeadragon)
  AucStatiLevel, v4.4.6991 (SwimmingSeadragon)
  AucStatPurchased, v4.4.6991 (SwimmingSeadragon)
  AucStatSimple, v4.4.6991 (SwimmingSeadragon)
  AucStatStdDev, v4.4.6991 (SwimmingSeadragon)
  AucUtilFixAH, v4.4.6991 (SwimmingSeadragon)
  BeanCounter, v4.4.6991 (SwimmingSeadragon)
  DBMCore, v10.2.46-4-ga5151a9
  DBMStatusBarTimers, v10.2.46-4-ga5151a9
  DBMVPVEM, vf7c7723
  Enchantrix, v4.4.6991 (SwimmingSeadragon)
  EnchantrixBarker, v4.4.6991 (SwimmingSeadragon)
  GatherMate2, v1.47.5-classic
  Informant, v4.4.6991 (SwimmingSeadragon)
  Questie, v10.2.5
  RareScanner, v4.4.0.3
  Recount, vv4.4.0a
  SlideBar, v4.4.6991 (SwimmingSeadragon)
  Stubby, v4.4.6991 (SwimmingSeadragon)
  Tukui, v@project-version@
  BlizRuntimeLib v4.4.0.55613(US) <enUS>
  (ck=3db)

**Comment by tukz** [comment]
if you downloaded from git, it may happen, because it doesn't include libs downloading this way. 

Please use this link for latest DEV version and let's me know if it still occur: 

https://api.tukui.org/v1/download/dev/tukui/live

**Comment by sidarthus89** [comment]
Which folder? Live or non-live
[cid:f9781330-18e2-4482-bcc6-344cebb2b448]
________________________________

**Comment by sidarthus89** [comment]
Downloaded from link above. #153 is still presnt

**Comment by sidarthus89** [comment]
![image](https://github.com/user-attachments/assets/df11dc0f-ea15-49e7-8300-45b1aa34a782)

**Comment by tukz** [comment]
This should be fixed in latest build.
