### ISSUE TITLE
Immersion add-on and Tukui mini map.  

### ISSUE THREAD

**Issue by pmb123** [tukui-org/Tukui#159]
Unsure if this is a Tukui or Immersion bug, but when "hide minimap" is selected in immersion, the Tukui minimap is not fully hidden; the borders disappear but the minimal frame itself persists
<img width="244" alt="Screenshot 2024-07-21 at 2 32 40 PM" src="https://github.com/user-attachments/assets/1b7e8a55-2d58-47b5-9d59-e903ef7d13f3">
<img width="270" alt="Screenshot 2024-07-21 at 2 33 03 PM" src="https://github.com/user-attachments/assets/bef806d5-c9fe-4282-a01f-90dd187d50b0">

**Comment by tukz** [comment]
Ehm, this is a immersion feature, so it should be an immersion issue.
