### ISSUE TITLE
Line Error

### ISSUE THREAD

**Issue by xuesemofa** [tukui-org/Tukui#160]
Message: ...Ons/Tukui/Modules/Miscellaneous/ObjectiveTracker.lua:561: attempt to index local 'Line' (a nil value)
Time: Tue Jul 23 12:57:43 2024
Count: 1
Stack: ...Ons/Tukui/Modules/Miscellaneous/ObjectiveTracker.lua:561: attempt to index local 'Line' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Tukui/Modules/Miscellaneous/ObjectiveTracker.lua"]:561: in function `Skin'
[string "@Interface/AddOns/Tukui/Modules/Miscellaneous/ObjectiveTracker.lua"]:691: in function `Enable'
[string "@Interface/AddOns/Tukui/Core/Loading.lua"]:273: in function <Interface/AddOns/Tukui/Core/Loading.lua:241>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by tukz** [comment]
Which version are you seeing this?

ERA, Classic, or Retail?

**Comment by xuesemofa** [comment]
Wrath of the Lich King - Chinese Special Edition(3.4.3.56030)
