### ISSUE TITLE
Game crashes in loading screen since the pre-patch

### ISSUE THREAD

**Issue by PotzBlitz45** [tukui-org/Tukui#161]
Hello, I don't know if I can send you any useful bugsack excerpts as I can't enter the game with ElvUi enabled.
Version is retail and i had ElvUi v. 13.70 and 13.71 after the pre-patch. When entering with a character I hear the error sound from bugsack and then the game crashes and is not responding. Disabling EvlUi lets me enter. I tried deleting everything from the addons folder and reinstalling even with deleted WTF folder and nothing changes. I can't get it to work. Does not matter if its a brand new character or an old one. What can I do to get you some error messages or is there any recommended actions I could take?

**Comment by tukz** [comment]
This is for Tukui, not ElvUI.
