### ISSUE TITLE
Irreversible overriding global variables

### ISSUE THREAD

**Issue by AdenJustice** [tukui-org/Tukui#164]
https://github.com/tukui-org/Tukui/blob/acd9a44a171f4569fd9932e67a367665c3c8fb93/Tukui/Modules/Fonts/Fonts.lua#L74

Once the global variables are overridden, they can't be reversed for the certain locales.

**Comment by Azilroka** [comment]
Those values are set before the configuration is imported for Tukui.

**Comment by AdenJustice** [comment]
> Those values are set before the configuration is imported for Tukui.

Sorry but I don't get it. 
I guess the intention of the codes is like, the three global variables should be overridden with tukui fonts for all locales, but for the three exceptional locales, tukui should use native fonts. But the execution wouldn't work like that.

**Comment by Azilroka** [comment]
Those 3 locales use cryllic or symbols not found in the fonts provided by Tukui. So it would be blocks like [] instead. So for those locales it should be using the default WoW UI fonts as the defaults.

If they customize it with other fonts after the fact it should still be honored.. because these are before the tukui saved variables are loaded and injected.

**Comment by AdenJustice** [comment]
> Those 3 locales use cryllic or symbols not found in the fonts provided by Tukui. So it would be blocks like [] instead. So for those locales it should be using the default WoW UI fonts as the defaults.
> 
> 
> 
> If they customize it with other fonts after the fact it should still be honored.. because these are before the tukui saved variables are loaded and injected.

Yes indeed. 
But the 3 lines before the line I cited (if ... clause) already overrides the default fonts with tukui's custom fonts even for the 3 locales too, so that the lines after that have no use. 

default fonts <- tukui fonts
if one of three locales then
tukui fonts <- **default fonts**

But **default fonts** are not default fonts anymore

**Comment by AdenJustice** [comment]
It should be "and" not "or"
