### ISSUE TITLE
Wrong Script setup

### ISSUE THREAD

**Issue by AdenJustice** [tukui-org/Tukui#171]
https://github.com/tukui-org/Tukui/blob/d920ad293c9519673b97c9959964d43edb4cce93/Tukui/Modules/DataTexts/Elements/Voice.lua#L101-L102

it seems `OnEnter` function for `OnEnter` event and `GameTooltip_Hide` for `OnLeave` event
there is no local function `OnLeave`

**Comment by Repooc** [comment]
> https://github.com/tukui-org/Tukui/blob/d920ad293c9519673b97c9959964d43edb4cce93/Tukui/Modules/DataTexts/Elements/Voice.lua#L101-L102
> 
> it seems `OnEnter` function for `OnEnter` event and `GameTooltip_Hide` for `OnLeave` event there is no local function `OnLeave`

line 48 and line 62
If I am wrong, reopen the ticket but quick glance, he has functions there.
