### ISSUE TITLE
Inappropriate type of an object

### ISSUE THREAD

**Issue by AdenJustice** [tukui-org/Tukui#173]
https://github.com/tukui-org/Tukui/blob/37712229f12e260067567cb76498f2b07841994c/Tukui/Modules/Miscellaneous/AltPowerBar.lua#L4

Just curious whether it's ok that the powerbar is declared as a button

https://github.com/tukui-org/Tukui/blob/37712229f12e260067567cb76498f2b07841994c/Tukui/Modules/Miscellaneous/AltPowerBar.lua#L76

`Enable` method of a button type is overridden consequently.

**Comment by Repooc** [comment]
While you are prob right the method, tukz never calls for an enable or disable to enable/disable the button as he just shows/hides the frame... That would be up to tukz to decide
