### ISSUE TITLE
undefined variable

### ISSUE THREAD

**Issue by AdenJustice** [tukui-org/Tukui#174]
https://github.com/tukui-org/Tukui/blob/c7324de44e36bb38b4405091795835e13d2670a4/Tukui/Modules/Miscellaneous/MirrorTimers.lua#L40

can't find `padding`

**Comment by AdenJustice** [comment]
https://github.com/tukui-org/Tukui/blob/c7324de44e36bb38b4405091795835e13d2670a4/Tukui/Modules/Miscellaneous/ThreatBar.lua#L113

maybe a mistake while copying and pasting?

**Comment by AdenJustice** [comment]
https://github.com/tukui-org/Tukui/blob/c7324de44e36bb38b4405091795835e13d2670a4/Tukui/Modules/UnitFrames/Core.lua#L116

`IsPvP` should have a boolean value not a function itself.

**Comment by AdenJustice** [comment]
`UnitIsPVP("player")` returns a value not a function

**Comment by Repooc** [comment]
Yeah i did it in a rush while working on 2 other things at the same time and didnt double check myself :P should be good now
