### ISSUE TITLE
weird logical condition

### ISSUE THREAD

**Issue by AdenJustice** [tukui-org/Tukui#175]
https://github.com/tukui-org/Tukui/blob/a2d647b32e7ff503be2b2f783e310cb5786e5dd1/Tukui/Modules/ActionBars/Bar1.lua#L14-L16

I think checking the existence of functions should be located out of `format()`

` local VehicleBar = GetVehicleBarIndex and format("[vehicleui][possessbar] %d;", GetVehicleBarIndex()) or ""`

**Comment by AdenJustice** [comment]
https://github.com/tukui-org/Tukui/blob/a2d647b32e7ff503be2b2f783e310cb5786e5dd1/Tukui/Modules/ActionBars/Bar1.lua#L96

https://github.com/tukui-org/Tukui/blob/a2d647b32e7ff503be2b2f783e310cb5786e5dd1/Tukui/Modules/ActionBars/Bar1.lua#L123

seems to need to change array name at line 96 to avoid duplicate var names

**Comment by AdenJustice** [comment]
https://github.com/tukui-org/Tukui/blob/a2d647b32e7ff503be2b2f783e310cb5786e5dd1/Tukui/Modules/ActionBars/Skin.lua#L153-L161

parameters `Name` and `Normal` are handed over but there are some redundant calling of functions and defining variables. not critical tho.

**Comment by AdenJustice** [comment]
https://github.com/tukui-org/Tukui/blob/a2d647b32e7ff503be2b2f783e310cb5786e5dd1/Tukui/Modules/ActionBars/Core.lua#L222
 
couldn't find any point to call the function. consequently, the following function is never called either. discarded?

https://github.com/tukui-org/Tukui/blob/a2d647b32e7ff503be2b2f783e310cb5786e5dd1/Tukui/Modules/ActionBars/Core.lua#L201

**Comment by Repooc** [comment]
you have all these little things in one ticket... split them up next time so they can be addressed individually next time.


> https://github.com/tukui-org/Tukui/blob/a2d647b32e7ff503be2b2f783e310cb5786e5dd1/Tukui/Modules/ActionBars/Bar1.lua#L14-L16
> 
> I think checking the existence of functions should be located out of `format()`
> 
> ` local VehicleBar = GetVehicleBarIndex and format("[vehicleui][possessbar] %d;", GetVehicleBarIndex()) or ""`

not really a big deal imo as it isnt hurting anything but did move it since the vars are only used on cata/retail and moved them to the location

**Comment by Repooc** [comment]
> https://github.com/tukui-org/Tukui/blob/a2d647b32e7ff503be2b2f783e310cb5786e5dd1/Tukui/Modules/ActionBars/Bar1.lua#L96
> 
> https://github.com/tukui-org/Tukui/blob/a2d647b32e7ff503be2b2f783e310cb5786e5dd1/Tukui/Modules/ActionBars/Bar1.lua#L123
> 
> seems to need to change array name at line 96 to avoid duplicate var names

prob not a big deal as all the instances looks to be shadowing an upvalue, if Tukz wants to refactor those, I will let him as I do not have the time to debug something I may screw up bc i altered something and didnt "see" it when i change it

Edit: I did make some changes but def needs testing, didnt have errors personally but like i said, i could have missed something

**Comment by Repooc** [comment]
> https://github.com/tukui-org/Tukui/blob/a2d647b32e7ff503be2b2f783e310cb5786e5dd1/Tukui/Modules/ActionBars/Skin.lua#L153-L161
> 
> parameters `Name` and `Normal` are handed over but there are some redundant calling of functions and defining variables. not critical tho.

I see nothing wrong with Name or Normal params as they are both used and dont see the issue, i removed one unused var for Cooldown
