### ISSUE TITLE
Error Message when dynamicaly updated progress bar is visible

### ISSUE THREAD

**Issue by Coruin** [tukui-org/Tukui#176]
Whenever there is some kind of progress bar (with timer) visible (on world object or npc), the following error code pops up and is constantly updated/repeated.

`Message: Frame:GetPoint(): Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: Frame:GetPoint().
Lua Taint: Tukui
Time: Thu Aug  8 13:13:08 2024
Count: 1
Stack: Frame:GetPoint(): Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: Frame:GetPoint().
Lua Taint: Tukui
[string "@Interface/AddOns/Tukui/Core/Toolkit.lua"]:129: in function `SetOutside'
[string "@Interface/AddOns/Tukui/Modules/Miscellaneous/UIWidgets.lua"]:21: in function <...ace/AddOns/Tukui/Modules/Miscellaneous/UIWidgets.lua:6>
[string "=[C]"]: in function `Setup'
[string "@Interface/AddOns/Blizzard_UIWidgets/Mainline/Blizzard_UIWidgetManager.lua"]:489: in function `ProcessWidget'
[string "@Interface/AddOns/Blizzard_UIWidgets/Mainline/Blizzard_UIWidgetManager.lua"]:52: in function <...zard_UIWidgets/Mainline/Blizzard_UIWidgetManager.lua:46>

Locals: self = Frame {
 Shadow = Frame {
 }
 BorderRight = Texture {
 }
 BorderLeft = Texture {
 }
 BorderBottom = Texture {
 }
 BorderTop = Texture {
 }
 Center = Texture {
 }
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 LeftEdge = Texture {
 }
}
Anchor = StatusBar {
 GlowCenter = Texture {
 }
 BGLeft = Texture {
 }
 BorderLeft = Texture {
 }
 tooltipLoc = 0
 displayedValue = 2851
 tooltipYOffset = 0
 value = 2851
 barText = "47 |4Minute:Minuten; 31 |4Sekunde:Sekunden;"
 GlowLeft = Texture {
 }
 barTextHasStyleSettings = 0
 tooltipContainsHyperLink = false
 Spark = Texture {
 }
 SparkMask = MaskTexture {
 }
 overrideBarTextShownType = 0
 tooltip = ""
 tooltipXOffset = 0
 partitionPool = <table> {
 }
 overrideBarText = ""
 barMinFillAlpha = 1
 barTextSizeType = 0
 barMin = 0
 barTextEnabledState = 3
 barValueTextType = 3
 barTextFontType = 1
 range = 3600
 barMaxFillAlpha = 1
 BackgroundGlow = Texture {
 }
 barMax = 3600
 Label = FontString {
 }
 GlowPulseAnim = AnimationGroup {
 }
 GlowRight = Texture {
 }
 BorderCenter = Texture {
 }
 tooltipAnchor = "ANCHOR_BOTTOMLEFT"
 BGRight = Texture {
 }
 defaultTooltipAnchor = "ANCHOR_BOTTOMLEFT"
 Backdrop = Frame {
 }
 BGCenter = Texture {
 }
 BorderRight = Texture {
 }
}
OffsetX = 0.999075
OffsetY = 0.999075
Toolkit = T00LKIT {
 Settings = <table> {
 }
 Functions = <table> {
 }
 API = <table> {
 }
 DefaultSettings = <table> {
 }
}
`

**Comment by RidleySin** [comment]
I too have this issue. closing the LUA Error screen just immediately reopens. Count ticks up like a timer.
![Screenshot 2024-08-09 082659](https://github.com/user-attachments/assets/7bada53f-6836-481f-9d04-018feeb1d54f)

**Comment by tukz** [comment]
Fixed.
