### ISSUE TITLE
Right actionbars overlapping bags SOD/Cata

### ISSUE THREAD

**Issue by Northion** [tukui-org/Tukui#182]
![2024-05-24_11_32_34-World_of_Warcraft](https://github.com/user-attachments/assets/f662ab2f-1b97-4097-a618-4453e591ec0a)

Fixed on Cata previously by setting Container:SetFrameStrata("LOW") to Container:SetFrameStrata("MEDIUM") on line 377 of bags.lua - This doesn't seem to work on SOD.
This seems to have been changed to LOW previously from this issue:
https://github.com/tukui-org/Tukui/issues/136

Is it possible to find a fix that works on both retail and classic cata+sod?

**Comment by tukz** [comment]
Not having this issue
![Screenshot 2024-09-16 142404](https://github.com/user-attachments/assets/650a79ce-25c4-4bb6-904e-9c28409426ae)

**Comment by Northion** [comment]
SOD: It starts out fine without overlap after the initial load of the game:
![2024-09-24 19_37_28-Window](https://github.com/user-attachments/assets/dd8afe7d-afae-4c5b-8cac-1ac78cf2ce63)

But after clicking one of abilities/buttons on the right bar, the abilities starts overlapping:
![2024-09-24 19_38_38-Window](https://github.com/user-attachments/assets/07646911-9111-4c9f-a41d-9e82cb7dbf29)
