### ISSUE TITLE
Interface Errors

### ISSUE THREAD

**Issue by The-Sickid** [tukui-org/Tukui#185]
As of right now the issue happens when I play a pally. When I build up my charges it brings up a big screen telling me that there is a interface error. I noticed that in Tukui for a pally; the UI only has 3 charges for the pally when in the default UI there is 5 charges. Just something to look into.

**Comment by Repooc** [comment]
should be fixed in the dev build already [https://api.tukui.org/v1/download/dev/tukui/live](https://api.tukui.org/v1/download/dev/tukui/live)
