### ISSUE TITLE
Missing Auras

### ISSUE THREAD

**Issue by Mcitra** [tukui-org/Tukui#190]
Hello.
I have had issues since DF on both my druid and other healers about missing auras on raidframes.

On druid, Lifebloom is not showing if it's talented with "Undergrowth" that make us have 2 Lifeblooms active. 
When not talented Lifebloom does show on raidframes.

Second issue is MAGIC debuffs on raidframes on some classes. On my druid and monk for example, it is not showing dispells if its magic that needs to be dispelled. This causes a big issue doing M+ keys as healers, is there a way to add magic dispells on raidframes for this season?

Big thank you in advance! I love the UI but these issues are becoming hard to have when doing high keys
Kind regards
Mcitra

**Comment by JerichoR** [comment]
Had a quick look at this already. 
1st issue: oUF_AuraTrack uses a whitelist for buffs, so likely adding that talent changes the spellid which is missing in the list. 
2nd issue: oUF_RaidDebuffs is super outdated, still looks for specs instead talents and spells. Maybe I can update that one.

**Comment by JerichoR** [comment]
https://github.com/tukui-org/Tukui/pull/191 should handle 2nd issue

AuraTrack looks ok though. Both Lifebloom versions are in retail section. Someone in Discord mentioned copying the Legendary version to the not retail tracker solves it, which would be weird.

**Comment by JerichoR** [comment]
oUF.isRetail variable was missing, so the classic tracker was always used. Likely many more spots throughout oUF silently failed there.
