### ISSUE TITLE
[BCC] Buffs and Debuffs not showing after update

### ISSUE THREAD

**Issue by t3hWheez** [tukui-org/Tukui#22]
`Message: Interface\FrameXML\SecureGroupHeaders.lua:1026: attempt to call field 'ForEachAura' (a nil value)
Time: Tue Mar 22 15:26:20 2022
Count: 2
Stack: Interface\FrameXML\SecureGroupHeaders.lua:1026: attempt to call field 'ForEachAura' (a nil value)
[string "@Interface\FrameXML\SecureGroupHeaders.lua"]:1026: in function `SecureAuraHeader_Update'
[string "@Interface\FrameXML\SecureGroupHeaders.lua"]:703: in function <Interface\FrameXML\SecureGroupHeaders.lua:698>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\SecureGroupHeaders.lua"]:682: in function <Interface\FrameXML\SecureGroupHeaders.lua:679>

Locals: self = TukuiBuffHeader {
 0 = <userdata>
 Backdrop = <unnamed> {
 }
 MoverName = "Buffs"
}
filter = "HELPFUL"
groupBy = nil
unit = "player"
includeWeapons = 1
consolidateTo = nil
consolidateDuration = nil
consolidateThreshold = nil
consolidateFraction = nil
sortDirection = nil
separateOwn = 0
sortMethod = <function> defined @Interface\FrameXML\SecureGroupHeaders.lua:938
time = 17410.972000
consolidateTable = nil
weaponPosition = 1
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "HELPFUL"
 HELPFUL = 1
}
(for control) = 1
filterIndex = 1
fullFilter = "HELPFUL"
i = 1
(*temporary) = nil
(*temporary) = "player"
(*temporary) = "HELPFUL"
(*temporary) = nil
(*temporary) = <function> defined @Interface\FrameXML\SecureGroupHeaders.lua:1026
(*temporary) = "attempt to call field 'ForEachAura' (a nil value)"
tonumber = <function> defined =[C]:-1
sorters = <table> {
 INDEX = <table> {
 }
 TIME = <table> {
 }
 NAME = <table> {
 }
 EXPIRES = <table> {
 }
}
wipe = <function> defined =[C]:-1
tokenTable = <table> {
}
sortingTable = <table> {
}
groupingTable = <table> {
 1 = "HELPFUL"
 HELPFUL = 1
}
stripRAID = <function> defined @Interface\FrameXML\SecureGroupHeaders.lua:881
ipairs = <function> defined =[C]:-1
freshTable = <function> defined @Interface\FrameXML\SecureGroupHeaders.lua:889
max = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
configureAuras = <function> defined @Interface\FrameXML\SecureGroupHeaders.lua:735
releaseTable = <function> defined @Interface\FrameXML\SecureGroupHeaders.lua:894
tremove = <function> defined =[C]:-1
`

`Message: Interface\FrameXML\SecureGroupHeaders.lua:1026: attempt to call field 'ForEachAura' (a nil value)
Time: Tue Mar 22 15:26:19 2022
Count: 1
Stack: Interface\FrameXML\SecureGroupHeaders.lua:1026: attempt to call field 'ForEachAura' (a nil value)
[string "@Interface\FrameXML\SecureGroupHeaders.lua"]:1026: in function <Interface\FrameXML\SecureGroupHeaders.lua:961>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Tukui\Modules\Auras\Headers.lua"]:73: in function `CreateHeaders'
[string "@Interface\AddOns\Tukui\Modules\Auras\Auras.lua"]:307: in function `Enable'
[string "@Interface\AddOns\Tukui\Core\Loading.lua"]:238: in function <Interface\AddOns\Tukui\Core\Loading.lua:226>

Locals: self = TukuiDebuffHeader {
 0 = <userdata>
 Backdrop = <unnamed> {
 }
}
filter = "HARMFUL"
groupBy = nil
unit = "player"
includeWeapons = nil
consolidateTo = nil
consolidateDuration = nil
consolidateThreshold = nil
consolidateFraction = nil
sortDirection = nil
separateOwn = 0
sortMethod = <function> defined @Interface\FrameXML\SecureGroupHeaders.lua:938
time = 17410.972000
consolidateTable = nil
weaponPosition = nil
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "HARMFUL"
 HARMFUL = 1
}
(for control) = 1
filterIndex = 1
fullFilter = "HARMFUL"
i = 1
(*temporary) = nil
(*temporary) = "player"
(*temporary) = "HARMFUL"
(*temporary) = nil
(*temporary) = <function> defined @Interface\FrameXML\SecureGroupHeaders.lua:1026
(*temporary) = "attempt to call field 'ForEachAura' (a nil value)"
tonumber = <function> defined =[C]:-1
sorters = <table> {
 INDEX = <table> {
 }
 TIME = <table> {
 }
 NAME = <table> {
 }
 EXPIRES = <table> {
 }
}
wipe = <function> defined =[C]:-1
tokenTable = <table> {
}
sortingTable = <table> {
}
groupingTable = <table> {
 1 = "HARMFUL"
 HARMFUL = 1
}
stripRAID = <function> defined @Interface\FrameXML\SecureGroupHeaders.lua:881
ipairs = <function> defined =[C]:-1
freshTable = <function> defined @Interface\FrameXML\SecureGroupHeaders.lua:889
max = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
configureAuras = <function> defined @Interface\FrameXML\SecureGroupHeaders.lua:735
releaseTable = <function> defined @Interface\FrameXML\SecureGroupHeaders.lua:894
tremove = <function> defined =[C]:-1
`

**Comment by UguMugu** [comment]
Sorry, but was this issue solved? Couldn't find any newer files about this.
