### ISSUE TITLE
can't see auras since patch 2.5.4

### ISSUE THREAD

**Issue by Isilrond** [tukui-org/Tukui#23]
had to disable the aura widget to see my buffs and debuffs

**Comment by UguMugu** [comment]
There was an Issue about this closed some hours ago, but I can't find a solution for it around here...

**Comment by Isilrond** [comment]
112x FrameXML\SecureGroupHeaders.lua:1026: attempt to call field 'ForEachAura' (a nil value)
[string "@FrameXML\SecureGroupHeaders.lua"]:1026: in function <FrameXML\SecureGroupHeaders.lua:961>
[string "=[C]"]: in function `Show'
[string "@Tukui\Modules\Auras\Headers.lua"]:60: in function `CreateHeaders'
[string "@Tukui\Modules\Auras\Auras-Auren.lua"]:307: in function `Enable'
[string "@Tukui\Core\Loading.lua"]:238: in function <Tukui\Core\Loading.lua:226>

Locals:
self = TukuiBuffHeader {
 0 = <userdata>
 Backdrop = <unnamed> {
 }
}
filter = "HELPFUL"
groupBy = nil
unit = "player"
includeWeapons = 1
consolidateTo = nil
consolidateDuration = nil
consolidateThreshold = nil
consolidateFraction = nil
sortDirection = nil
separateOwn = 0
sortMethod = <function> defined @FrameXML\SecureGroupHeaders.lua:938
time = 419341.648000
consolidateTable = nil
weaponPosition = 1
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "HELPFUL"
 HELPFUL = 1
}
(for control) = 1
filterIndex = 1
fullFilter = "HELPFUL"
i = 1
(*temporary) = nil
(*temporary) = "player"
(*temporary) = "HELPFUL"
(*temporary) = nil
(*temporary) = <function> defined @FrameXML\SecureGroupHeaders.lua:1026
(*temporary) = "attempt to call field 'ForEachAura' (a nil value)"
tonumber = <function> defined =[C]:-1
sorters = <table> {
 INDEX = <table> {
 }
 TIME = <table> {
 }
 NAME = <table> {
 }
 EXPIRES = <table> {
 }
}
wipe = <function> defined =[C]:-1
tokenTable = <table> {
}
sortingTable = <table> {
}
groupingTable = <table> {
 1 = "HELPFUL"
 HELPFUL = 1
}
stripRAID = <function> defined @FrameXML\SecureGroupHeaders.lua:881
ipairs = <function> defined =[C]:-1
freshTable = <function> defined @FrameXML\SecureGroupHeaders.lua:889
max = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
configureAuras = <function> defined @FrameXML\SecureGroupHeaders.lua:735
releaseTable = <function> defined @FrameXML\SecureGroupHeaders.lua:894
tremove = <function> defined =[C]:-1

**Comment by t3hWheez** [comment]
I closed mine because on the Discord someone said this was caused by something on Blizzards end.

**Comment by Repooc** [comment]
should be fine on wow build > 2.5.4.42873

**Comment by UguMugu** [comment]
Thank you
