### ISSUE TITLE
[BCC] Latest WoW update causes chat issues

### ISSUE THREAD

**Issue by t3hWheez** [tukui-org/Tukui#24]
A Voice chat tab has appeared and is unable to be removed no matter what settings I choose.

Performing a /tukui chat reset puts General on the right and keeps Voice.

![Screenshot 2022-03-23 093806](https://user-images.githubusercontent.com/62818470/160515466-ad7d3950-510e-42f6-aab1-da1ab519877f.png)

**Comment by martinjango** [comment]
Going to Interface > Accessibility > checking and unchecking "Speak for me in voice chat" removes the window.

**Comment by martinjango** [comment]
Going to Interface > Accessibility > checking and unchecking "Speak for me in voice chat" removes the window.

**Comment by t3hWheez** [comment]
That works to remove it, thanks!

However the issue persists if you do a /tukui chat reset

If I remember correctly 'Other' should be on the right, not the left.  If you perform the above command it brings the Voice tab back.
