### ISSUE TITLE
Lua error while hovering over left character datatext in Classic SoM

### ISSUE THREAD

**Issue by Lou62** [tukui-org/Tukui#28]
Hello.

I seem to be getting a lua error when I mouseover the left character datatext in Classic SoM. I have no other addons installed and I have also tried all of the download versions of Tukui. Any help would be greatly appreciated.

Thanks.

![WoWScrnShot_052022_060841](https://user-images.githubusercontent.com/105903872/169458269-bb3aacf1-588e-44f3-9ae1-4a2a14c017ad.jpg)

**Comment by Repooc** [comment]
fixed in latest commits not yet released yet
