### ISSUE TITLE
Pvp timer on player unitframe missing

### ISSUE THREAD

**Issue by Teuf86** [tukui-org/Tukui#30]
Hi there!
First I wanna say thank you for the great job you all do for us, players! I really love this UI!

I recently realized that when exiting pvp mode, the timer can't be found anywhere (5 minutes timer in friendly zone). 
For example, I play in the Horde and was in Orgrimmar. I enabled PVP and then disabled it, but the timer can't be found anywhere. I only use Tukui as Addon, nothing else and am playing on a fresh installation (Artix). Otherwise, everything else works great, this is the only issue I have.

If you need more information, let me know!

Thanks 

Edit : September 13th (2 weeks later..) : Issue still present

**Comment by tukz** [comment]
This can be seen in the War Mode panel.
