### ISSUE TITLE
WOTLK classic shaman does not have totem bar for managing totems

### ISSUE THREAD

**Issue by mikec83** [tukui-org/Tukui#31]
When using tukui with the latest wow classic patch for WOTLK and playing a shaman, there is currently no way for a shaman to manage their totems without disabling tukui entirely.

**Comment by tukz** [comment]
You can right click ton the totem bar (or square) depending of your current setting to manage them.

**Comment by tukz** [comment]
Add new MultiCastBar for WOTLK, just reinstall.
