### ISSUE TITLE
[WotLK] Unitframe out of range fading is incorrect range for healers

### ISSUE THREAD

**Issue by t3hWheez** [tukui-org/Tukui#36]
When players in my raid frames go out of range and their frame fades, in BCC I would never be able to heal them.  Since WotLK release if a player goes out of range it does not appear to be the correct 40 yard range for healers.  I am still able to heal people when their frames have faded.

**Comment by stva23** [comment]
Can confirm this as Priest.

**Comment by t3hWheez** [comment]
I know you are busy Tuk and we appreciate your work but would really love to get this resolved.

Thanks for all your hard work!

**Comment by tukz** [comment]
Seem to work fine for me? flash heal is 40 yards, as you can see on my animated gif, it fade correctly at correct range. Maybe something i'm missing?

![WowClassicT_h5dMiSR7VU](https://user-images.githubusercontent.com/168442/213941224-da0ceadb-404e-46ae-b958-eef81989fca1.gif)

**Comment by t3hWheez** [comment]
Here it is in real time.  

https://youtu.be/9Hxit6Gc_Fw

**Comment by tukz** [comment]
Did a little change in 20.37 pushed 5 mins ago. Let's me know if it's better.

**Comment by stva23** [comment]
Its only in the Unitframe, not the Targetwindow. Doesnt work for me with latest commit.

**Comment by t3hWheez** [comment]
Still happening - here is what I have tried:

Removing all WTF files related to Tukui
Disabling all addons besides Tukui
Changing the range check spellID to various spells with no luck

I have no idea what the issue is - if I have time today I can try and create a level 1 character to see if the same applies.

**Comment by t3hWheez** [comment]
Still an issue, please help!

**Comment by stva23** [comment]
I tested now with 2 new Priests (on 2 Accounts). Clean WTF, all addons beside Tukui disabled. It works correctly! 

I think now we have to figure out why its not working on old setups. Disabling Addons/Clean Tukui Settings doesnt help...

Thanks that u are still working on this, if u have any ideas how we could help testing and investigating let us know!

**Comment by t3hWheez** [comment]
I wonder if I remove my profile it would fix.. but a clean WTF should have been the same thing?

**Comment by stva23** [comment]
Using a new Tukui profile doesnt work for my main priest. I already tried.
