### ISSUE TITLE
[WotLK] Lua Error for opening bag

### ISSUE THREAD

**Issue by Slimsmoky** [tukui-org/Tukui#37]
Hi,
for 2 days now, Iam getting a Lua Error everytime the bag is opening. Even if Tukui is the only addon loaded.
![image](https://user-images.githubusercontent.com/115328622/194680027-feac6af0-f285-4d24-9bd5-72cc89b1df21.png)

Fun fact:
The error seem to occure only on my LvL 80 main-character. On my LvL 1 bankcharacters, the Lua Error doesn`t appear...
Even with Tukui the only addon loaded.

Thx for help.

UPDATE:
A workaround came from "Istian" (Discord). Un-ticking the new currency tracker "Show on Backpack" from the character menu fixed the Lua Error.

**Comment by tukz** [comment]
Should be fixed, reinstall.
