### ISSUE TITLE
Action bars gone + Guild Master abilities blocked

### ISSUE THREAD

**Issue by Gladd0s** [tukui-org/Tukui#38]
In WOTLK Classic all the action bars have disappeared. Several people reported this error in the Tukui Community discord [(link to message here)](https://discord.com/channels/209244641537556480/831222083937763368/1029349116771319871). 
The other issue is that as soon as you try to demote/promote anyone in the guild, the action gets blocked. The only way around it has been to disable tukui, change roles of people, then enable tukui again.
![Screenshot 2022-10-11 163617](https://user-images.githubusercontent.com/87989697/195120953-0c167a3f-63a4-459d-99c5-a45b209852f9.png)
![unknown](https://user-images.githubusercontent.com/87989697/195121089-0e44ac5d-882e-4e7d-a348-7f5039fb80e8.png)

**Comment by DrTTrousers** [comment]
Can confirm that this was fine ~9 hours ago during lunch but is now dumping an error on every login

 ```
Message: Interface\FrameXML\ChatFrame.lua:3419: attempt to index local 'info' (a nil value)
 Time: Tue Oct 11 21:33:19 2022
 Count: 1
 Stack: Interface\FrameXML\ChatFrame.lua:3419: attempt to index local 'info' (a nil value)
 [string "=[C]"]: ?
 [string "@Interface\FrameXML\ChatFrame.lua"]:3419: in function `ChatFrame_MessageEventHandler'
 [string "@Interface\AddOns\Tukui\Modules\ChatFrames\ChatHistory.lua"]:38: in function `Print'
 [string "@Interface\AddOns\Tukui\Modules\ChatFrames\ChatHistory.lua"]:63: in function `OnEvent'
 [string "@Interface\AddOns\Tukui\Modules\ChatFrames\ChatHistory.lua"]:83: in function `Enable'
 [string "@Interface\AddOns\Tukui\Modules\ChatFrames\ChatFrames.lua"]:815: in function `Enable'
 [string "@Interface\AddOns\Tukui\Core\Loading.lua"]:243: in function <Interface\AddOns\Tukui\Core\Loading.lua:226>
 
 Locals: 
```

**Comment by gg-chrisd** [comment]
Seems to be related to the SavedVariables Tukui.lua file.

If you delete your Tukui.lua file in C:\Games\World of Warcraft\_classic_\WTF\Account\{account name}\SavedVariables folder it resets your config and gets things back up and running (albeit back at default settings), but it's only a temporary fix, as next login it seems to break again.

**Comment by gg-chrisd** [comment]
Turns out this is related to the Chat settings.

`/tukui c` > Chat > Log Message History > Set to 0 and Apply.

**Comment by jrdalenberg** [comment]
> Turns out this is related to the Chat settings.
> 
> `/tukui c` > Chat > Log Message History > Set to 0 and Apply.

Same problem, and confirming that this indeed solves the issue.

That was quite an eventful raid yesterday in which I lost my action bars after a relog xD

**Comment by Gladd0s** [comment]
The issue with guild management did exist prior to the actionbar errors and I believe it still exists
