### ISSUE TITLE
[Retail] Interface issues after updating Tukui to 20.30 (WoW 10.0.0.46340)

### ISSUE THREAD

**Issue by Coruin** [tukui-org/Tukui#43]
Since updating Tukui to 20.30 after the release of the dragonflight pre-patch I get multiple errors in the game:

1. Stance bar randomly moving from there location atop of the left chat window to above the character unit frame (screenshot 1)
2. Tukui gets randomly blocked because it allegedly uses some blizz-exclusive functions (screenshot 1)

using /rl fixes both until their next random occurrence

3. debuffs are shown double (screenshot 2)
4. when in a group, the default unitframes are sometimes shown alongside the tukui frames (screenshot 3)

There are some more "minor" issues, like item icons not showing when opening the bag/bank for the first time or no visible information regarding the dungeon finder queue.

I get no lua error message whenever these issues happen. Before opening a ticket here, I also tried deleting the interface folder and doing a clean install of tukui, but the issues persist.

Screenshot 1:
![screenshot 1](https://user-images.githubusercontent.com/13752163/198672840-68ad7600-9a0b-4ddd-8ac6-aa8ac5c9de76.png)

Screenshot 2:
![screenshot 2](https://user-images.githubusercontent.com/13752163/198672846-20d3b7cb-cab6-4316-a9cc-04991242ee99.png)

Screenshot 3:
![screenshot 3](https://user-images.githubusercontent.com/13752163/198672833-52d5fc90-6ea2-4e00-bb01-80fa5d484f98.png)

**Comment by tukz** [comment]
These should be fixed, reinstall.
