### ISSUE TITLE
[WOTLK] Aura display issues

### ISSUE THREAD

**Issue by nitowa** [tukui-org/Tukui#49]
Tukui v20.31 currently has these issues with displaying de/buff durations

Unitframe buff timers show two duration texts on buffs

![double duration text](https://i.imgur.com/Lp7aGR8.png)

Unitframe debuff timers fail to show up, or only show up with <10s remaining

![debuff duration issue](https://i.imgur.com/GiapI6W.png)

This issue is mirrored on nameplates

![debuff duration issue on nameplate](https://i.imgur.com/4irenpP.png)

Unrelated to this issue, a feature request:

Currently display of debuffs on friendly targets is controlled by the "Only show our debuffs on target" option. With this option turned on, it is not possible to see debuffs on friendly targets which can make tasks like tank swaps difficult. The option should probably not apply to friendly targets or non-player sources in general.

**Comment by tukz** [comment]
Should be fix.
