### ISSUE TITLE
[retail] right bar#1+#2 Frame drop..

### ISSUE THREAD

**Issue by gayxx** [tukui-org/Tukui#50]
If enable right bar#1(actionbar#4) and right bar#2(actionbar#5) together,
   --you mouseover to another target after the battle begins, frame drop is very severe

there is no problem if you use only one of the two.....

sorry,  I'm using a translator :)

**Comment by gayxx** [comment]
If enable right bar#1 and right bar#2 together, >> The frame drop is very severe when the target is changed after the start of the battle. 

there is no problem if you use only one of the two.....

 
> leave a comment with a translator. sorry:)

**Comment by gayxx** [comment]
mage,warlock class have problems. :(

**Comment by gayxx** [comment]
> mage,warlock,dk class have problems. :(

![제목 없음](https://user-images.githubusercontent.com/117508188/200117047-84de8811-96a2-4b7f-bceb-026a4657b5e4.png)

What's the problem?  help me please

**Comment by Coruin** [comment]
Seems to be the same issue like #47

**Comment by tukz** [comment]
Should be fixed, let's me know after reinstall.

**Comment by gayxx** [comment]
> Should be fixed, let's me know after reinstall.



> Should be fixed, let's me know after reinstall.

**Comment by gayxx** [comment]
> Should be fixed, let's me know after reinstall.
