### ISSUE TITLE
[Retail] Hide friendly buffs

### ISSUE THREAD

**Issue by gayxx** [tukui-org/Tukui#63]
![제목 없음](https://user-images.githubusercontent.com/117508188/202835977-4ce50fcf-108d-4da8-99e3-19d25a92c111.png)

From the Tukui DF version, you can see 3 friendly buffs..
Can't you hide this buff?

It was not seen in the tukui SL version...
I only want to see the stealing buff on the nameplate.

**Comment by tukz** [comment]
The buffs that can be stealed will be animated in version 20.36+, like it was previously in SL version. It was a bug until 20.36.
