### ISSUE TITLE
Issue with Raid Window / Raid Info Window

### ISSUE THREAD

**Issue by UguMugu** [tukui-org/Tukui#64]
Hi. 
When I open my raid window, this LUA Error pops up:

Message: Interface_Wrath\FrameXML\RaidFrame.lua:165: attempt to index a nil value
Time: Sun Nov 20 19:11:02 2022
Count: 2
Stack: Interface_Wrath\FrameXML\RaidFrame.lua:165: attempt to index a nil value
[string "@Interface_Wrath\FrameXML\RaidFrame.lua"]:165: in function `RaidInfoFrame_Update'
[string "@Interface_Wrath\FrameXML\RaidFrame.lua"]:82: in function `RaidFrame_OnEvent'
[string "@Interface_Wrath\AddOns\Blizzard_RaidUI\Blizzard_RaidUI.lua"]:169: in function <...ace_Wrath\AddOns\Blizzard_RaidUI\Blizzard_RaidUI.lua:168>

Locals: savedInstances = 13
instanceName = "Gundrak"
instanceID = 209252237
instanceReset = 46138
instanceDifficulty = "Heroic"
(for index) = 11
(for limit) = 13
(for step) = 1
i = 11
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = true
(*temporary) = nil
(*temporary) = 3
(*temporary) = nil
(*temporary) = "12 |4Hr:Hr; 48 |4Min:Min;"
(*temporary) = 2
(*temporary) = "attempt to index a nil value"

Gundrak and Uthgarde Pinnacle are in the same spot (like overwritten) in the Raid Info window. Not 100 % sure if it's only those two when both are ID'ed or it's just the 2nd and 3rd position.

**Comment by tukz** [comment]
This is a blizzard issue, and maybe it was fixed with the patch this week. Not Tukui related.
