### ISSUE TITLE
occasional error hotkey usage on action bar

### ISSUE THREAD

**Issue by Gillm09** [tukui-org/Tukui#66]
error pops up and actionbar keys unusable. Reload ui fixes it.

**Comment by Dvaina** [comment]
Same Problem on Retail.
Any keybind on actionbar3 results in following error:
Clicking actionbar3 is fine.  Keybinds on actionbar1 are also fine. 
Error reappears after every loading screen and is only fixed by reloading the UI.
Can someone please help me?
```

23x [ADDON_ACTION_FORBIDDEN] AddOn 'Tukui' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@FrameXML/MultiActionBars.lua"]:14: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR3BUTTON8"]:2: in function <[string "MULTIACTIONBAR3BUTTON8"]:1>
```

**Comment by lajtika** [comment]
22x [ADDON_ACTION_FORBIDDEN] AddOn 'Tukui' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@FrameXML/MultiActionBars.lua"]:14: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR1BUTTON11"]:2: in function <[string "MULTIACTIONBAR1BUTTON11"]:1>

**Comment by tukz** [comment]
This should be already fixed since a month.
