### ISSUE TITLE
Can't see the minimap buton for factions fame progress 

### ISSUE THREAD

**Issue by SIIVA97** [tukui-org/Tukui#72]
i Just installed Tukui after being with Elvui for the most part of my experience, but i can't find the button that used to be on the minimap to see my fame progress with all four faction. Is it just me or do i need to enablr it on the options? cause i've been checking for 30 minutes and still can't find it

**Comment by Coruin** [comment]
You can open it by using mouse button 3 (scroll wheel button) on the minimap.

**Comment by Grunskin** [comment]
> You can open it by using mouse button 3 (scroll wheel button) on the minimap.

This works. Can't believe I went over a month without knowing this. Thank you!
