### ISSUE TITLE
[WOTLK] No vehicle bar at malygos

### ISSUE THREAD

**Issue by jeroz1** [tukui-org/Tukui#81]
I did not get a vehicle bar at Malygos just now. I am using [6480d9c](https://github.com/tukui-org/Tukui/commit/6480d9c90bd8709280c27c02015af0975bdad561).

The vehicle bar was not available at all. Also not after scrolling through bars.

**Comment by tukz** [comment]
This should be fixed if you reinstall. Thanks for the report!
