### ISSUE TITLE
[WOTLK[ LUA error when targeting

### ISSUE THREAD

**Issue by Deejaybee27** [tukui-org/Tukui#82]
Getting this error when targeting even after update 

Message: Interface/AddOns/Tukui/Libs/oUF/elements/auras.lua:232: bad argument #1 to 'SetText' (Usage: self:SetText([text]))
Time: Wed Jan 18 17:06:47 2023
Count: 174
Stack: Interface/AddOns/Tukui/Libs/oUF/elements/auras.lua:232: bad argument #1 to 'SetText' (Usage: self:SetText([text]))

Locals:

**Comment by Deejaybee27** [comment]
Seems to be a problem with displaying buffs on unitframes. Error does not stop when disabling aura module. Don't know anything other than that.

**Comment by tukz** [comment]
Already fixed, reinstall :)
