### ISSUE TITLE
[RETAIL] Bags 

### ISSUE THREAD

**Issue by MisschaStokebroek** [tukui-org/Tukui#89]
Opening the bank and then opening the bank reagent tab hides the reagentslots for the normal bag.
Closing the bank reagents tab doesn't bring back bag reagent slots,  reload fixes it.

Clicking the arrow on the bagsframe to show the seperate bags now shows the blizzard bagsbar (mostly bottom of the screen) instead of the skinned and anchored bagsslots at the topright of the bagsframe.

**Comment by pedrozc90** [comment]
Fixed on [Pull Request #90](https://github.com/tukui-org/Tukui/pull/90)
